parameters:
  DB_HOST: '%env(DB_HOST)%'
  DB_NAME: '%env(DB_NAME)%'
  DB_USER: '%env(DB_USER)%'
  DB_PASSWORD: '%env(DB_PASSWORD)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
        resource: '../src/'

  App\Lib\DatabaseConfig:
    arguments:
      $host: '%DB_HOST%'
      $dbname: '%DB_NAME%'
      $user: '%DB_USER%'
      $password: '%DB_PASSWORD%'

  App\Lib\Application:
    public: true
    arguments:
      $controllerProvider: !service_locator
        employee: '@App\Controller\EmployeeController'
        departement: '@App\Controller\DepartementController'

  Symfony\Component\HttpFoundation\Session\Session:

  Symfony\Component\HttpFoundation\Session\SessionInterface: '@Symfony\Component\HttpFoundation\Session\Session'

  Twig\Loader\FilesystemLoader:
    arguments:
      $paths:
        - './templates'

  Twig\Environment:
    arguments:
      $loader: '@Twig\Loader\FilesystemLoader'

  Symfony\Component\Routing\Router:
    arguments:
      $loader: '@Symfony\Component\Routing\Loader\YamlFileLoader'
      $resource: 'routes.yaml'

  Symfony\Component\Routing\RouterInterface:
    alias: Symfony\Component\Routing\Router

  Symfony\Component\Config\FileLocator:
    arguments:
      $paths:
        - './config'

  Symfony\Component\Routing\Loader\YamlFileLoader:
    arguments:
      $locator: '@Symfony\Component\Config\FileLocator'

  Symfony\Component\Routing\RouteCollection:
    factory: ['@Symfony\Component\Routing\Loader\YamlFileLoader', 'load']
    arguments:
      - 'routes.yaml'

  Twig\TwigFunction:
    arguments:
      $name: 'path'
      $callable: ['@Symfony\Component\Routing\Router', 'generate']

  App\Lib\TwigRouterConfigurator:
    arguments:
      $twig: '@Twig\Environment'
      $router: '@Symfony\Component\Routing\Router'
    calls:
      - method: 'configure'
        arguments: []

