parameters:
  DB_HOST: '%env(DB_HOST)%'
  DB_NAME: '%env(DB_NAME)%'
  DB_USER: '%env(DB_USER)%'
  DB_PASSWORD: '%env(DB_PASSWORD)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Lib\DatabaseConfig:
    arguments:
      $host: '%DB_HOST%'
      $dbname: '%DB_NAME%'
      $user: '%DB_USER%'
      $password: '%DB_PASSWORD%'

  App\Lib\DatabaseConnection:

  App\Lib\QueryBuilder:

  App\Lib\Application:
    public: true
    arguments:
      - !service_locator
          Employee: '@App\Controller\EmployeeController'
          Departement: '@App\Controller\DepartementController'

  App\Model\EmployeeModel:

  App\Model\DepartementModel:

  App\Controller\EmployeeController:

  App\Controller\DepartementController:

